// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKzOVnRtbEmHE3PCIwaBuyZ8C6bclmWwI',
    appId: '1:489261314104:android:3733c72051329d4ae1f6cd',
    messagingSenderId: '489261314104',
    projectId: 'contacts-app-70c22',
    storageBucket: 'contacts-app-70c22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEf_xaP7I7Mc0F1a46dUTGYWU_RZwlf0o',
    appId: '1:489261314104:ios:43c2d2bcd4fc70b4e1f6cd',
    messagingSenderId: '489261314104',
    projectId: 'contacts-app-70c22',
    storageBucket: 'contacts-app-70c22.appspot.com',
    androidClientId: '489261314104-mm1490pdlfqlhnb4i98snresmig8t1fm.apps.googleusercontent.com',
    iosClientId: '489261314104-eisgg4m42mil1jvnufpjjomb5o6pgk4c.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactsApp',
  );
}
